--문) 캐나다 지사에서 근무하고 있는 직원들의 이름을 인쇄하십시오.

SELECT FIRST_NAME || '' || LAST_NAME AS NAME FROM (SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN
			  							  		  (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID IN
			  							  		  (SELECT LOCATION_ID FROM LOCATIONS WHERE COUNTRY_ID IN 
			  							  		  (SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_ID = 'CA'))))