-- 테이블 작성1
INSERT INTO DEV.TENPOLIST_TB(TEMPO_NO, ADDRESS, NAME, PRICE) 
VALUES('1','秋葉原','うさぎや','2000');

INSERT INTO DEV.TENPOLIST_TB(TEMPO_NO, ADDRESS, NAME, PRICE) 
VALUES('2','亀有','美味しいくまや第一','2000');

INSERT INTO DEV.TENPOLIST_TB(TEMPO_NO, ADDRESS, NAME, PRICE) 
VALUES('3','上野','くまや第二','3500');

INSERT INTO DEV.TENPOLIST_TB(TEMPO_NO, ADDRESS, NAME, PRICE) 
VALUES('4','岩本町','エスパーニャ','3000');

-- TEST
SELECT * FROM TENPOLIST_TB ORDER BY TEMPO_NO ASC;

-- 1. tenpolistに「うなぎ」店を追加するDMLを作成せよ。 住所は「上野」　予算は「7000」
INSERT INTO DEV.TENPOLIST_TB(TEMPO_NO, ADDRESS, NAME, PRICE) 
VALUES('5','上野','うなぎ','7000');

-- 2. 予算が「7000」未満の店件数を取得せよ
SELECT COUNT(TEMPO_NO) AS "PIRCE<7000" 
FROM TENPOLIST_TB 
WHERE PRICE < 7000;

-- 3. 住所が「上野」或は「予算」が「3000」以上の店舗番号と店舗名を取得せよ
SELECT * 
FROM TENPOLIST_TB 
WHERE ADDRESS = '上野' 
OR PRICE >= 3000
ORDER BY TEMPO_NO;

-- 4. 予算が「3000」以上と[7000]以下の間の店舗の平均値
SELECT AVG(PRICE) 
FROM TENPOLIST_TB 
WHERE PRICE >= 3000
AND PRICE <= 7000;

-- 5. 住所が「上野」もしくは「名前」に「くまや」が含まれている店舗の「合計額」を取得
SELECT SUM(PRICE)
FROM TENPOLIST_TB
WHERE ADDRESS = '上野'
OR NAME LIKE '%くまや%';

-- 6. 店舗番号が「２」以上の店舗を取得せよ　ただし「予算」降順で
SELECT * 
FROM TENPOLIST_TB
WHERE TEMPO_NO >= 2
ORDER BY PRICE DESC;
